{"content": {"suites": {"0": {"status": {"total_pass": 6, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test01", "rerun": "0"}, "1": {"status": "FAIL", "message": "           pytest_assume.plugin.FailedAssumption: \n           1 Failed Assumptions:\n           \n           test_case\\test_project_G4.py:368: AssumptionFailure\n           >>\tcircle_check_result = pytest.assume(self.g4_d(resourceId=\"com.abupdate.fota_demo_iot:id/tv_new_version\").exists(timeout=180))\n           AssertionError: assert False\n", "test_name": "test02", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test03", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test04", "rerun": "0"}, "4": {"status": "FAIL", "message": "           socket.timeout: timed out\n       urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x000002180F5537F0>, 'Connection to 192.168.43.1 timed out. (connect timeout=3)')\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.43.1', port=7912): Max retries exceeded with url: /jsonrpc/0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002180F5537F0>, 'Connection to 192.168.43.1 timed out. (connect timeout=3)'))\n               requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.43.1', port=7912): Max retries exceeded with url: /jsonrpc/0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002180F5537F0>, 'Connection to 192.168.43.1 timed out. (connect timeout=3)'))\n", "test_name": "test05", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test06", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test07", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test08", "rerun": "0"}}, "suite_name": "test_case/test_project_G4.py"}}}, "date": "February 07, 2021", "start_time": 1612697858, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "6", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "8"}